name = "hospital-outbreak-dashboard"
main = "src/index.ts" # Adjust if your entry point is different
compatibility_date = "2024-04-05"

# D1 Database configuration
[[d1_databases]]
binding = "DB" # How you'll access it in your Worker/Pages Function
database_name = "outbreak-db" # Choose a name for your database
database_id = "" # This will be filled in after creation
preview_database_id = "outbreak-db-preview" # Use a different name for preview/local dev
migrations_dir = "migrations"

[dev]
port = 3001 # Port for local development server

# Add other configurations as needed, e.g., environment variables
# [vars]
# MY_VAR = "some_value"


pages_build_output_dir = ".next"
